#!/bin/bash
#SBATCH -A DEEPSCIENCE
#SBATCH -N 1
#SBATCH -J keras-ae
#SBATCH -t 72:00:00
#SBATCH -p shared
#SBATCH --gres=gpu:1
 
module purge
module load cuda
 
pyenv local anaconda2-5.2.0
python train_auto_encoder.py
